### ISSUE TITLE
Cacti 1.1.21 + Quicktree v1.0.0-beta.2

### ISSUE THREAD

**Issue by jpobeda** [netniV/cacti-quicktree#1]
Hi @netniV 

Thanks for reworking quicktree to work with 1.x!

I added a couple of graphs and then when I go to Quicktree tab and click on one of them, it takes me to the graph tab but it doesn't appear to be loading the timespan filter and showing this error instead.

![image](https://user-images.githubusercontent.com/13456559/34958486-0972ce4e-fa97-11e7-8c76-e77746ae23cc.png)

```
2018/01/16 08:25:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph.php: 48 top_graph_header)(/lib/functions.php: 3450 include)(/include/top_graph_header.php: 130 draw_navigation_text)(/lib/functions.php: 2714 CactiErrorHandler)(/lib/functions.php: 4421 cacti_debug_backtrace)
--
2018/01/16 08:25:23 - ERROR PHP NOTICE: Undefined index: graph.php:update_timespan in file: /usr/share/cacti-1.1.21/lib/functions.php on line: 2714
2018/01/16 08:25:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph.php: 48 top_graph_header)(/lib/functions.php: 3450 include)(/include/top_graph_header.php: 130 draw_navigation_text)(/lib/functions.php: 2713 CactiErrorHandler)(/lib/functions.php: 4421 cacti_debug_backtrace)
2018/01/16 08:25:23 - ERROR PHP NOTICE: Undefined index: graph.php:update_timespan in file: /usr/share/cacti-1.1.21/lib/functions.php on line: 2713
2018/01/16 08:25:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph.php: 48 top_graph_header)(/lib/functions.php: 3450 include)(/include/top_graph_header.php: 63 draw_navigation_text)(/lib/functions.php: 2714 CactiErrorHandler)(/lib/functions.php: 4421 cacti_debug_backtrace)
2018/01/16 08:25:23 - ERROR PHP NOTICE: Undefined index: graph.php:update_timespan in file: /usr/share/cacti-1.1.21/lib/functions.php on line: 2714
2018/01/16 08:25:23 - CMDPHP PHP ERROR NOTICE Backtrace: (/graph.php: 48 top_graph_header)(/lib/functions.php: 3450 include)(/include/top_graph_header.php: 63 draw_navigation_text)(/lib/functions.php: 2713 CactiErrorHandler)(/lib/functions.php: 4421 cacti_debug_backtrace)
2018/01/16 08:25:23 - ERROR PHP NOTICE: Undefined index: graph.php:update_timespan in file: /usr/share/cacti-1.1.21/lib/functions.php on line: 2713
```
Sorry for opening this issue under /cacti but Howie hasn't merged your PR yet.

**Comment by jpobeda** [comment]
Cacti 1.1.21 but if it's not present on the latest releases don't worry.

I'll upgrade it sometime after testing.

**Comment by netniV** [comment]
Well, I've marked the plugin as being 1.1.9 compliant but if it isn't, need to fix that :)

**Comment by netniV** [comment]
Oh and are you using 1.0-beta or 1.0-beta.2?

**Comment by jpobeda** [comment]
I've downloaded it from your repository, the rework branch.

This is what Plugin mgmt shows

QuickTree for Cacti 1.x | Active | Howard Jones | 1.0.0

I haven't seen those options anywhere. Am I missing something?

**Comment by jpobeda** [comment]
Ups, just noticed that you packed the releases hehe. I downloaded the rework branch yesterday.

**Comment by netniV** [comment]
That should be the 1.0.0-beta.2 then.  I'll take a look now see if I can see anything.

**Comment by netniV** [comment]
This is a strange error because it appears to be related to a caching of the title for the bedcrumbs etc.  Now the interesting part is that I can not get that error to occur even on 1.1.21 of cacti.

This makes me wonder if it's something in your graph title causing the problem.

**Comment by jpobeda** [comment]
I think I skipped a few steps. Do this:

1.- Add a couple of graphs to quicktree
2.- go to quicktree tab and click on one of them
3.- Select a time span using the 3 click move. At this point, you should see that selecting the time frame doesn't do anything, right?
4.- Press F5 there.

**Comment by netniV** [comment]
Yeah I see the problem now.  I think that is because we don't have a tree selected, just the graph itself.  This may have always been an issue, or at least with 1.x of cacti.  I'm investigating further.

**Comment by netniV** [comment]
It would appear to be a bug with Cacti itself not me.  If you click on the List View mode, then click the graph, then highlight a selection, it fails :)

👎

**Comment by jpobeda** [comment]
You're right! :(

I was right then opening the issue under /cacti (?) hehe

**Comment by netniV** [comment]
That is correct, apparently 👍   As you can see I've created the appropriate issue over there and referenced it here too. Closing this now.
